[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["kuviman <kuviman@gmail.com>"]
categories = ["game-engines"]
description = "Game ENGine"
# documentation = ""
edition = "2021"
homepage = "https://geng.kuviman.com"
keywords = ["game", "engine", "gamedev", "geng"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kuviman/geng"
version = "0.14.0"

[workspace.dependencies]
batbox = { version = "0.14", path = "crates/batbox" }
batbox-derive = { version = "0.14", path = "crates/batbox-derive" }
batbox-macros = { version = "0.14", path = "crates/batbox-macros" }

# Geng
geng = { version = "0.14", path = "crates/geng" }
geng-derive = { version = "0.14", path = "crates/geng-derive" }
geng-ui-macros = { version = "0.14", path = "crates/geng-ui-macros" }

# Ugli
ugli = { version = "0.14", path = "crates/ugli" }
ugli-derive = { version = "0.14", path = "crates/ugli-derive" }
ugli-raw = { version = "0.14", path = "crates/ugli-raw" }

# Common
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
toml = "0.5"
ron = "0.8"
rand = "0.8"
# https://github.com/rust-random/rand#wasm-support
getrandom = { version = "0.2", features = ["js"] }
log = "0.4"
clap = { version = "4", features = ["derive"] }
url = "2"
futures = "0.3"
pin-utils = "0.1"
once_cell = "1"
bincode = "1"
dyn-clone = "1"
maplit = "1"
env_logger = "0.10"
backtrace = "0.3"
thiserror = "1"
anyhow = "1" # TODO: eyre?
async-trait = "0.1"
derive_more = "0.99"
itertools = "0.10"
derivative = "2"
rusttype = { version = "0.9", features = [
    "gpu_cache",
] } # TODO: not used anymore?
ttf-parser = "0.18"
lazy_static = "1" # TODO remove
flate2 = "1"
atomic_float = "0.1"
num_enum = "0.5"
gltf = "1"
http = "0.2"

# Native
libc = "0.2"
tinyfiledialogs = "3"
directories = "4"
image = "0.24"
glutin = "0.29" # TODO update
threadpool = "1"
num_cpus = "1"
notify = "5"
rodio = { git = "https://github.com/kuviman/rodio", branch = "mp3-duration" } # TODO
ws = "0.9"
gl = "0.14"
async-std = "1"
reqwest = { version = "0.11", features = [
    "stream",
    "rustls-tls",
], default-features = false }
async-compat = "0.2"

# Web
wasm-opt = "0.110"
wasm-bindgen-cli-support = "0.2"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Storage",
    "Navigator",
    "Location",
    "XmlHttpRequestResponseType",
    "ProgressEvent",
    "Document",
    "DistanceModelType",
    "CssStyleDeclaration",
    "HtmlAudioElement",
    "XmlHttpRequest",
    "XmlHttpRequestResponseType",
    "KeyboardEvent",
    "MouseEvent",
    "WheelEvent",
    "TouchEvent",
    "Touch",
    "TouchList",
    "DomRect",
    "DomRectReadOnly",
    "WebSocket",
    "BinaryType",
    "MessageEvent",
    "HtmlCanvasElement",
    "AngleInstancedArrays",
    "OesStandardDerivatives",
    "WebGlRenderingContext",
    "WebGlBuffer",
    "WebGlActiveInfo",
    "WebGlUniformLocation",
    "WebGlTexture",
    "WebGlRenderbuffer",
    "WebGlProgram",
    "WebGlFramebuffer",
    "WebGlShader",
    "HtmlImageElement",
    "HtmlInputElement",
    "MediaElementAudioSourceNode",
    "PannerNode",
    "AudioListener",
    "BaseAudioContext",
    "AudioContext",
    "AudioDestinationNode",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioParam",
    "GainNode",
    "Performance",
    "Response",
    "ReadableStream",
    "FileList",
    "File",
    "Url",
    "HtmlAnchorElement",
    "ExtBlendMinmax",
] }
wasm-streams = "0.3"

# Proc macros
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
darling = "0.14"

# cargo-geng specific
open = "3"
tokio = { version = "1", features = ["rt-multi-thread", "full"] }
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }
hyper-staticfile = "0.9"
fs_extra = "1"
cargo_metadata = "0.15"
