[package]
name = "geng"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[features]
default = ["audio"]
audio = ["dep:geng-audio"]

[dev-dependencies]
gltf.workspace = true
geng-net-simple.workspace = true

[dependencies]
batbox.workspace = true
geng-window.workspace = true
geng-net.workspace = true
geng-camera.workspace = true
geng-shader.workspace = true
geng-font.workspace = true
geng-audio = { workspace = true, optional = true }
geng-ui.workspace = true
geng-state.workspace = true
geng-draw2d.workspace = true
geng-obj.workspace = true
geng-debug-overlay.workspace = true
geng-asset.workspace = true
geng-texture-atlas.workspace = true
ugli.workspace = true

gilrs.workspace = true
serde.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
wasm-bindgen.workspace = true
