[package]
name = "geng-audio"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dev-dependencies]
futures.workspace = true

[dependencies]
anyhow.workspace = true
geng-web-audio-api.workspace = true
batbox-la.workspace = true
batbox-time.workspace = true
batbox-file.workspace = true
