[package]
name = "ugli-raw"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
batbox.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gl.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys = { workspace = true, features = [
    "HtmlImageElement",
    "HtmlCanvasElement",
    "AngleInstancedArrays",
    "OesStandardDerivatives",
    "WebGlRenderingContext",
    "WebGlBuffer",
    "WebGlActiveInfo",
    "WebGlUniformLocation",
    "WebGlTexture",
    "WebGlRenderbuffer",
    "WebGlProgram",
    "WebGlFramebuffer",
    "WebGlShader",
    "ExtBlendMinmax",
] }
