[package]
name = "ugli"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
batbox-tuple-macros.workspace = true
batbox-color.workspace = true
batbox-la.workspace = true
batbox-range.workspace = true
thiserror.workspace = true
ugli-raw.workspace = true
ugli-derive.workspace = true
field-offset.workspace = true
log.workspace = true
derive_more.workspace = true

num_enum.workspace = true # TODO: should be in batbox?
serde.workspace = true
image.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
serde-wasm-bindgen.workspace = true
web-sys.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin.workspace = true
